#!/bin/bash
modprobe libcomposite

cd /sys/kernel/config/usb_gadget/
mkdir -p myusbstick
cd myusbstick
echo 0x14dd > idVendor # Raritan
echo 0x1010 > idProduct # DKX4-101
echo 0x0111 > bcdDevice # v1.0.0
echo 0x0200 > bcdUSB # USB2

mkdir -p strings/0x409
echo "abcdef0123456789" > strings/0x409/serialnumber
echo "Andreas Stamm" > strings/0x409/manufacturer
echo "absolute mouse test device" > strings/0x409/product

mkdir -p configs/c.1/strings/0x409
echo "Config 1: ECM network" > configs/c.1/strings/0x409/configuration
echo 250 > configs/c.1/MaxPower

# OS descriptors
mkdir -p os_desc
echo "1"       > os_desc/use
echo "0xcd"    > os_desc/b_vendor_code
echo "MSFT100" > os_desc/qw_sign

ln -s configs/c.1 os_desc

# absolute mouse
mkdir -p functions/hid.usb0
echo 1 > functions/hid.usb0/protocol
echo 1 > functions/hid.usb0/subclass
echo 6 > functions/hid.usb0/report_length
echo -ne \\x05\\x01\\x09\\x02\\xA1\\x01\\x09\\x01\\xA1\\x00\\x05\\x09\\x19\\x01\\x29\\x05\\x15\\x00\\x25\\x01\\x95\\x05\\x75\\x01\\x81\\x02\\x75\\x03\\x95\\x01\\x81\\x03\\x05\\x01\\x09\\x30\\x09\\x31\\x15\\x00\\x26\\xFF\\x7F\\x75\\x10\\x95\\x02\\x81\\x02\\x09\\x38\\x15\\x81\\x25\\x7F\\x75\\x08\\x95\\x01\\x81\\x06\\xC0\\xC0 > functions/hid.usb0/report_desc
ln -s functions/hid.usb0 configs/c.1/

udevadm settle -t 5 || :
ls /sys/class/udc > UDC
udevadm settle -t 5 || :

python /home/<USERNAME>/absolute_mouse_test.py &